# Generated by Django 3.2.15 on 2023-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station_app', '0002_bonuscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='LoyaltyСard',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
