# Generated by Django 3.2.15 on 2023-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station_app', '0003_alter_bonuscard_loyaltyсard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankСard', models.CharField(max_length=50, unique=True)),
                ('CardHolder', models.CharField(max_length=255)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
    ]
